name: voice_control_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_dotenv: ^2.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.13.0
  hooks_riverpod: ^0.6.1
  state_notifier: ^0.6.0
  speech_to_text: ^2.4.1
  flutter_tts: ^1.2.6
  ibm_watson_assistant: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
